FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:jammy

# Dependecies

# Packages

# Download sdk

# Set the Flutter environment path

# Run the flutter doctor

# Set it up for the web

# Setup 

# Pull in files from Git to a container 

# make server executable 
